# PyTorch Fundamentals

## 1. Matrices

### 1.1 Creating matrices

In [1]:
import numpy as np

In [2]:
arr = [[1,2], [3,4]]
np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch

In [ ]:
### 1.1 Create tensors

In [14]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

### 1.2 Create matrices with default values

In [24]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [25]:
np.random.rand(2, 2)

array([[ 0.03453992,  0.9407207 ],
       [ 0.6675943 ,  0.29846383]])

In [26]:
np.random.randn(2, 2)

array([[ 1.70578156, -0.1322996 ],
       [ 0.45192063,  0.05872406]])

In [17]:
torch.rand((2,2))


 0.1591  0.8898
 0.1201  0.0767
[torch.FloatTensor of size 2x2]

In [18]:
torch.randn((2,2))


 0.0951 -0.0390
-1.1703 -0.6539
[torch.FloatTensor of size 2x2]

### 1.3 Seeds for reproducibility

In [36]:
np.random.seed(1)
np.random.randn(2,2)

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862]])

In [40]:
np.random.randn(2,2)

array([[-0.17242821, -0.87785842],
       [ 0.04221375,  0.58281521]])

Let's try that again...

In [41]:
np.random.seed(1)
np.random.randn(2,2)

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862]])

In [42]:
 np.random.randn(2,2)

array([[ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ]])

And not let's do the same in PyTorch

In [44]:
torch.manual_seed(1)
torch.rand(2,2)


 0.7576  0.2793
 0.4031  0.7347
[torch.FloatTensor of size 2x2]

In [46]:
torch.rand(2,2)


 0.0293  0.7999
 0.3971  0.7544
[torch.FloatTensor of size 2x2]

In [47]:
torch.manual_seed(1)
torch.rand(2,2)


 0.7576  0.2793
 0.4031  0.7347
[torch.FloatTensor of size 2x2]

In [48]:
torch.rand(2,2)


 0.0293  0.7999
 0.3971  0.7544
[torch.FloatTensor of size 2x2]

Seed for GPU

In [49]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1)

### 1.3 Numpy and Torch bridge

#### Numpyt to Torch

In [51]:
np_arr = np.ones((2,2))

In [52]:
torch.from_numpy(np_arr)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

Notice the type of tensor created

In [53]:
type(torch.from_numpy(np_arr))

torch.DoubleTensor

In [55]:
np_arr_2 = np.ones((2,2), dtype=np.int8)
torch.from_numpy(np_arr_2)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

** This conversion only supports : **
    1. double
    2. float
    3. uint8, int32, int64

In [59]:
np_arr_3 = np.ones((2,2), dtype=np.int64)
torch.from_numpy(np_arr_3)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [60]:
np_arr_4 = np.ones((2,2), dtype=np.int32)
torch.from_numpy(np_arr_4)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [61]:
np_arr_5 = np.ones((2,2), dtype=np.uint8)
torch.from_numpy(np_arr_5)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [62]:
np_arr_6 = np.ones((2,2), dtype=np.float)
torch.from_numpy(np_arr_6)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [63]:
np_arr_7 = np.ones((2,2), dtype=np.float)
torch.from_numpy(np_arr_7)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

#### Torch to Numpy

In [66]:
torch_tensor = torch.ones(2,2)
type(torch_tensor)

torch.FloatTensor

In [68]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

### 1.4 Tensor on CPU to GPU

In [69]:
# CPU tensor
tensor_cpu = torch.ones(2,2)

In [71]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [72]:
# GPU to CPU
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

### 1.5 Tensor operations

#### Resizing a tensor

In [74]:
a = torch.ones(2,2)

In [75]:
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [76]:
print (a.size())

torch.Size([2, 2])


In [77]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [78]:
a.view(1,4)


 1  1  1  1
[torch.FloatTensor of size 1x4]

In [79]:
a.view(4, 1)


 1
 1
 1
 1
[torch.FloatTensor of size 4x1]

In [80]:
a.view(4,1,1)


(0 ,.,.) = 
  1

(1 ,.,.) = 
  1

(2 ,.,.) = 
  1

(3 ,.,.) = 
  1
[torch.FloatTensor of size 4x1x1]

#### Elementwise operations

In [83]:
a = torch.ones(2,2)
print (a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [84]:
b = torch.ones(2,2)
print (b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [85]:
c = a+b
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [86]:
c = torch.add(a,b)

In [87]:
c


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [94]:
c = a.add(b)

In [95]:
c


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [88]:
# Inplace addition
c.add_(a)


 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [89]:
c


 3  3
 3  3
[torch.FloatTensor of size 2x2]

**Subtraction**

In [90]:
c = a - b

In [91]:
c


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [92]:
c = a.sub(b)

In [93]:
c


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [96]:
# Inplace
c = a + b
c.sub_(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [97]:
c


 1  1
 1  1
[torch.FloatTensor of size 2x2]

**Multiplication**

In [98]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [99]:
a*b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [100]:
torch.mul(a,b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [101]:
a.mul_(b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [102]:
a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

**Division**

In [104]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [105]:
torch.div(b, a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [106]:
torch.div(a,b)


inf inf
inf inf
[torch.FloatTensor of size 2x2]

In [107]:
b.div_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [108]:
b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

**Tensor mean**

In [109]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
np_a = np.arange(1, 11)
print(np_a.mean())

5.5


In [121]:
a = torch.Tensor(np_a)

In [122]:
a.size()

torch.Size([10])

In [123]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [124]:
a.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [129]:
l = [i for i in range(1,11)]
a = torch.Tensor([l, l])

In [130]:
a


    1     2     3     4     5     6     7     8     9    10
    1     2     3     4     5     6     7     8     9    10
[torch.FloatTensor of size 2x10]

In [131]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

In [132]:
a.mean(dim=0)


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
[torch.FloatTensor of size 10]

**Torch standard deviation**

In [133]:
a = torch.Tensor(l)

In [134]:
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]

In [135]:
a.var(dim=0)


 9.1667
[torch.FloatTensor of size 1]